import { reactive } from 'vue';
interface DevIcons {
  name: string;
  icon: string;
}

export const skillIcons: DevIcons[] = reactive([
  { name: 'Aarch 64', icon: 'aarch64' },
  { name: 'Adonis JS', icon: 'adonisjs' },
  { name: 'Adobe AfterEffects', icon: 'aftereffects' },
  { name: 'Akka', icon: 'akka' },
  { name: 'Angolia', icon: 'algolia' },
  { name: 'Alpinejs', icon: 'alpinejs' },
  { name: 'Amazon Web Services', icon: 'amazon-web-services' },
  { name: 'Anaconda', icon: 'anaconda' },
  { name: 'Android Studio', icon: 'android-studio' },
  { name: 'Android', icon: 'android' },
  { name: 'Angular', icon: 'angular' },
  { name: 'Angular JS', icon: 'angularjs' },
  { name: 'Angular Material', icon: 'angular-material' },
  { name: 'Ansible', icon: 'ansible' },
  { name: 'Ant Design', icon: 'ant-design' },
  { name: 'Apache', icon: 'apache' },
  { name: 'Apache Airflow', icon: 'apache-airflow' },
  { name: 'Apache Kafka', icon: 'apache-kafka' },
  { name: 'Apache Spark', icon: 'apache-spark' },
  { name: 'Apl', icon: 'apl' },
  { name: 'Appcelerator', icon: 'appcelerator' },
  { name: 'Apple', icon: 'apple' },
  { name: 'AppWrite', icon: 'appwrite' },
  { name: 'Arch Linux', icon: 'arch-linux' },
  { name: 'Arduino', icon: 'arduino' },
  { name: 'Argo CD', icon: 'argocd' },
  { name: 'Astro', icon: 'astro' },
  { name: 'Atom', icon: 'atom' },
  { name: 'AWK', icon: 'awk' },
  { name: 'Axios', icon: 'axios' },
  { name: 'Microsoft Azure', icon: 'azure' },
  { name: 'Azure DevOps', icon: 'azure-devops' },
  { name: 'Azure SQL Database', icon: 'azure-sql-database' },

  // B
  { name: 'Babel', icon: 'babel' },
  { name: 'Backbone JS', icon: 'backbonejs' },
  { name: 'Ballerina', icon: 'ballerina' },
  { name: 'Bamboo', icon: 'bamboo' },
  { name: 'Bash', icon: 'bash' },
  { name: 'Beats', icon: 'beats' },
  { name: 'Behance', icon: 'behance' },
  { name: 'Bit Bucket', icon: 'bitbucket' },
  { name: 'Blazor', icon: 'blazor' },
  { name: 'Blender', icon: 'blender' },
  { name: 'Bootstrap', icon: 'bootstrap' },
  { name: 'Browerstack', icon: 'browserstack' },
  { name: 'Bulma CSS', icon: 'bulmacss' },
  { name: 'Bun', icon: 'bun' },

  // C
  { name: 'C', icon: 'c' },
  { name: 'Cairo', icon: 'cairo' },
  { name: 'Cake PHP', icon: 'cake-php' },
  { name: 'Canva', icon: 'canva' },
  { name: 'Capacitor', icon: 'capacitor' },
  { name: 'Carbon', icon: 'carbon' },
  { name: 'Cassandra', icon: 'cassandra' },
  { name: 'Centos', icon: 'centos' },
  { name: 'Ceylon', icon: 'ceylon' },
  { name: 'Chrome', icon: 'chrome' },
  { name: 'Circle CI', icon: 'circleci' },
  { name: 'Clarity', icon: 'clarity' },
  { name: 'Clion', icon: 'clion' },
  { name: 'Clojure', icon: 'clojure' },
  { name: 'Clojure Script', icon: 'clojurescript' },
  { name: 'Cloudflare', icon: 'cloudflare' },
  { name: 'Cloudflare Workers', icon: 'cloudflare-workers' },
  { name: 'C Make', icon: 'cmake' },
  { name: 'Codeac', icon: 'codeac' },
  { name: 'Codecov', icon: 'codecov' },
  { name: 'Code Igniter', icon: 'codeigniter' },
  { name: 'Code Pen', icon: 'codepen' },
  { name: 'Coffeescript', icon: 'coffeescript' },
  { name: 'Composer', icon: 'composer' },
  { name: 'Confluence', icon: 'confluence' },
  { name: 'Consul', icon: 'consul' },
  { name: 'Contao', icon: 'contao' },
  { name: 'Core JS', icon: 'corejs' },
  { name: 'Cosmos DB', icon: 'cosmosdb' },
  { name: 'Couchbase', icon: 'couchbase' },
  { name: 'Couch DB', icon: 'couchdb' },
  { name: 'C Plus Plus', icon: 'cplusplus' },
  { name: 'Crystal', icon: 'crystal' },
  { name: 'C Sharp', icon: 'csharp' },
  { name: 'CSS', icon: 'css3' },
  { name: 'Cucumber', icon: 'cucumber' },
  { name: 'Cypress', icon: 'cypress' },

  // D
  { name: 'D3 JS', icon: 'd3js' },
  { name: 'Dart', icon: 'dart' },
  { name: 'Data Grip', icon: 'datagrip' },
  { name: 'Data Spell', icon: 'dataspell' },
  { name: 'Dbeaver', icon: 'dbeaver' },
  { name: 'Debian', icon: 'debian' },
  { name: 'Deno JS', icon: 'denojs' },
  { name: 'Devicon', icon: 'devicon' },
  { name: 'DIgital Ocean', icon: 'digitalocean' },
  { name: 'Discord JS', icon: 'discordjs' },
  { name: 'Django', icon: 'django' },
  { name: 'Django REST', icon: 'djangorest' },
  { name: 'Docker', icon: 'docker' },
  { name: 'Doctrine', icon: 'doctrine' },
  { name: 'Dot Net', icon: 'dot-net' },
  { name: 'Dot Net Core', icon: 'dotnetcore' },
  { name: 'Adobe Dreamweaver', icon: 'dreamweaver' },
  { name: 'Drop Wizard', icon: 'dropwizard' },
  { name: 'Drupal', icon: 'drupal' },
  { name: 'Dynamo DB', icon: 'dynamodb' },

  // E
  { name: 'Eclipse', icon: 'eclipse' },
  { name: 'Ecto', icon: 'ecto' },
  { name: 'Elastic Search', icon: 'elastic-search' },
  { name: 'Electron', icon: 'electron' },
  { name: 'Eleventy', icon: 'eleventy' },
  { name: 'Elixir', icon: 'elixir' },
  { name: 'Elm', icon: 'elm' },
  { name: 'Emacs', icon: 'emacs' },
  { name: 'Embeddedc', icon: 'embeddedc' },
  { name: 'Ember', icon: 'ember' },
  { name: 'Envoy', icon: 'envoy' },
  { name: 'Erlang', icon: 'erlang' },
  { name: 'Eslint', icon: 'eslint' },
  { name: 'Express JS', icon: 'express' },

  // F
  { name: 'Facebook', icon: 'facebook' },
  { name: 'FastApi', icon: 'fastapi' },
  { name: 'Fastify', icon: 'fastify' },
  { name: 'Fauna DB', icon: 'faunadb' },
  { name: 'Feathers JS', icon: 'feathersjs' },
  { name: 'Fedora', icon: 'fedora' },
  { name: 'Figma', icon: 'figma' },
  { name: 'File Zilla', icon: 'filezilla' },
  { name: 'Firebase', icon: 'firebase' },
  { name: 'FireFox', icon: 'firefox' },
  { name: 'Flask', icon: 'flask' },
  { name: 'Flutter', icon: 'flutter' },
  { name: 'Fortran', icon: 'fortran' },
  { name: 'Foundation', icon: 'foundation' },
  { name: 'Framer Motion', icon: 'framer-motion' },
  { name: 'Framework 7', icon: 'framework7' },
  { name: 'F Sharp', icon: 'fsharp' },

  // G
  { name: 'Gatling', icon: 'gatling' },
  { name: 'Gatsby', icon: 'gatsby' },
  { name: 'Gazebo', icon: 'gazebo' },
  { name: 'GCC', icon: 'gcc' },
  { name: 'Gentoo', icon: 'gentoo' },
  { name: 'Ghost', icon: 'ghost' },
  { name: 'Gimp', icon: 'gimp' },
  { name: 'Git', icon: 'git' },
  { name: 'Git Book', icon: 'gitbook' },
  { name: 'Github', icon: 'github' },
  { name: 'Github Action', icon: 'github-actions' },
  { name: 'Github Codespaces', icon: 'github-codespaces' },
  { name: 'Gitlab', icon: 'gitlab' },
  { name: 'Gitpod', icon: 'gitpod' },
  { name: 'Gitter', icon: 'gitter' },
  { name: 'Go', icon: 'go' },
  { name: 'Godot', icon: 'godot' },
  { name: 'Goland', icon: 'goland' },
  { name: 'Google', icon: 'google' },
  { name: 'Google Cloud', icon: 'google-cloud' },
  { name: 'Gradle', icon: 'gradle' },
  { name: 'Grafana', icon: 'grafana' },
  { name: 'Grails', icon: 'grails' },
  { name: 'Graph QL', icon: 'graphql' },
  { name: 'Groovy', icon: 'groovy' },
  { name: 'GRPC', icon: 'grpc' },
  { name: 'Grunt', icon: 'grunt' },
  { name: 'Gulp', icon: 'gulp' },

  // H
  { name: 'Hadoop', icon: 'hadoop' },
  { name: 'Handlebars', icon: 'handlebars' },
  { name: 'Hard Hat', icon: 'hardhat' },
  { name: 'Harvester', icon: 'harvester' },
  { name: 'Haskell', icon: 'haskell' },
  { name: 'Haxe', icon: 'haxe' },
  { name: 'Helm', icon: 'helm' },
  { name: 'Heroku', icon: 'heroku' },
  { name: 'Hibernate', icon: 'hibernate' },
  { name: 'Homebrew', icon: 'homebrew' },
  { name: 'HTML', icon: 'html5' },
  { name: 'Hugo', icon: 'hugo' },

  // I
  { name: 'Internet Explorer', icon: 'ie10' },
  { name: 'IFTTT', icon: 'ifttt' },
  { name: 'Adobe Illustrator', icon: 'illustrator' },
  { name: 'Influx DB', icon: 'influxdb' },
  { name: 'Inkscape', icon: 'inkscape' },
  { name: 'Insomnia', icon: 'insomnia' },
  { name: 'Intelli J', icon: 'intellij' },
  { name: 'Ionic', icon: 'ionic' },

  // J
  { name: 'Jaegertracing', icon: 'jaegertracing' },
  { name: 'Jamstack', icon: 'jamstack' },
  { name: 'Jasmine', icon: 'jasmine' },
  { name: 'Java', icon: 'java' },
  { name: 'JavaScript', icon: 'javascript' },
  { name: 'Jeet', icon: 'jeet' },
  { name: 'Jekyll', icon: 'jekyll' },
  { name: 'Jenkins', icon: 'jenkins' },
  { name: 'Jest', icon: 'jest' },
  { name: 'Jetbrain', icon: 'jetbrain' },
  { name: 'Jetpack Compose', icon: 'jetpack-compose' },
  { name: 'Jira', icon: 'jira' },
  { name: 'Jira Align', icon: 'jira-align' },
  { name: 'Jquery', icon: 'jquery' },
  { name: 'Json', icon: 'json' },
  { name: 'Jule', icon: 'jule' },
  { name: 'Julia', icon: 'julia' },
  { name: 'Junit', icon: 'junit' },
  { name: 'Jupyter', icon: 'jupyter' },

  //K
  { name: 'K3 OS', icon: 'k3os' },
  { name: 'K3S', icon: 'k3s' },
  { name: 'K6', icon: 'k6' },
  { name: 'Kaggle', icon: 'kaggle' },
  { name: 'Karate Labs', icon: 'karatelabs' },
  { name: 'Karma', icon: 'karma' },
  { name: 'Kdeneon', icon: 'kdeneon' },
  { name: 'Keras', icon: 'keras' },
  { name: 'Kibana', icon: 'kibana' },
  { name: 'Knex JS', icon: 'knexjs' },
  { name: 'Kotlin', icon: 'kotlin' },
  { name: 'Kraken JS', icon: 'krakenjs' },
  { name: 'Ktor', icon: 'ktor' },
  { name: 'Kubernetes', icon: 'kubernetes' },

  // L
  { name: 'Lab View', icon: 'labview' },
  { name: 'Laravel', icon: 'laravel' },
  { name: 'Latex', icon: 'latex' },
  { name: 'Less', icon: 'less' },
  { name: 'LinkedIn', icon: 'linkedin' },
  { name: 'Linux', icon: 'linux' },
  { name: 'Liqui Base', icon: 'liquibase' },
  { name: 'Livewire', icon: 'livewire' },
  { name: 'LLVM', icon: 'llvm' },
  { name: 'Lodash', icon: 'lodash' },
  { name: 'Log Stash', icon: 'logstash' },
  { name: 'Lua', icon: 'lua' },
  { name: 'Lumen', icon: 'lumen' },

  // M
  { name: 'Magento', icon: 'magento' },
  { name: 'Maria DB', icon: 'mariadb' },
  { name: 'Markdown', icon: 'markdown' },
  { name: 'Materialize CSS', icon: 'materializecss' },
  { name: 'Material UI', icon: 'materialui' },
  { name: 'Matlab', icon: 'matlab' },
  { name: 'Matplot Lib', icon: 'matplotlib' },
  { name: 'Maven', icon: 'maven' },
  { name: 'Maya', icon: 'maya' },
  { name: 'Meteor', icon: 'meteor' },
  { name: 'Microsoft SQL Server', icon: 'microsoft-sql-server' },
  { name: 'Minitab', icon: 'minitab' },
  { name: 'Mithril', icon: 'mithril' },
  { name: 'Mobx', icon: 'mobx' },
  { name: 'Mocha', icon: 'mocha' },
  { name: 'Modx', icon: 'modx' },
  { name: 'Moleculer', icon: 'moleculer' },
  { name: 'Mongo DB', icon: 'mongodb' },
  { name: 'Mongoose', icon: 'mongoose' },
  { name: 'Moodle', icon: 'moodle' },
  { name: 'MS DOS', icon: 'msdos' },
  { name: 'MySql', icon: 'mysql' },

  // N
  { name: 'Nano', icon: 'nano' },
  { name: 'Neo4J', icon: 'neo4j' },
  { name: 'NeoVim', icon: 'neovim' },
  { name: 'Nest JS', icon: 'nestjs' },
  { name: 'Netlify', icon: 'netlify' },
  { name: 'NetworkX', icon: 'networkx' },
  { name: 'NEXT JS', icon: 'nextjs' },
  { name: 'NGINX', icon: 'nginx' },
  { name: 'NGRX', icon: 'ngrx' },
  { name: 'N Hibernate', icon: 'nhibernate' },
  { name: 'Nim', icon: 'nim' },
  { name: 'Nimble', icon: 'nimble' },
  { name: 'Nixos', icon: 'nixos' },
  { name: 'Node JS', icon: 'nodejs' },
  { name: 'Nodemon', icon: 'nodemon' },
  { name: 'Node Webkit', icon: 'nodewebkit' },
  { name: 'Nomad', icon: 'nomad' },
  { name: 'Norg', icon: 'norg' },
  { name: 'Notion', icon: 'notion' },
  { name: 'NPM', icon: 'npm' },
  { name: 'Nuget', icon: 'nuget' },
  { name: 'Numpy', icon: 'numpy' },
  { name: 'Nuxt JS', icon: 'nuxtjs' },

  // M
  { name: 'O Auth', icon: 'oauth' },
  { name: 'Objective C', icon: 'objective-c' },
  { name: 'Ocaml', icon: 'ocaml' },
  { name: 'Ohmyzsh', icon: 'ohmyzsh' },
  { name: 'Okta', icon: 'okta' },
  { name: 'Open AL', icon: 'openal' },
  { name: 'Open API', icon: 'openapi' },
  { name: 'Open CL', icon: 'opencl' },
  { name: 'Open CV', icon: 'opencv' },
  { name: 'Open GL', icon: 'opengl' },
  { name: 'Open Stack', icon: 'openstack' },
  { name: 'Nuxt ', icon: 'opensuse' },
  { name: 'Open Telemetry', icon: 'opentelemetry' },
  { name: 'Opera', icon: 'opera' },
  { name: 'Oracle', icon: 'oracle' },
  { name: 'Ory', icon: 'ory' },

  // P

  { name: 'P5 JS', icon: 'p5js' },
  { name: 'Packer', icon: 'packer' },
  { name: 'Pandas', icon: 'pandas' },
  { name: 'Perl', icon: 'perl' },
  { name: 'PFsense', icon: 'pfsense' },
  { name: 'Phalcon', icon: 'phalcon' },
  { name: 'Phoenix', icon: 'phoenix' },
  { name: 'Photonengine', icon: 'photonengine' },
  { name: 'Photoshop', icon: 'photoshop' },
  { name: 'PHP', icon: 'php' },
  { name: 'PhpStorm', icon: 'phpstorm' },
  { name: 'Playwright', icon: 'playwright' },
  { name: 'Plotly', icon: 'plotly' },
  { name: 'Pnpm', icon: 'pnpm' },
  { name: 'Podman', icon: 'podman' },
  { name: 'Poetry', icon: 'poetry' },
  { name: 'Polygon', icon: 'polygon' },
  { name: 'Portainer', icon: 'portainer' },
  { name: 'PostCSS', icon: 'postcss' },
  { name: 'PostgreSQL', icon: 'postgresql' },
  { name: 'Postman', icon: 'postman' },
  { name: 'Power Shell', icon: 'powershell' },
  { name: 'Premierè Pro', icon: 'premierepro' },
  { name: 'prisma', icon: 'prisma' },
  { name: 'Processing', icon: 'processing' },
  { name: 'Prolog', icon: 'prolog' },
  { name: 'Prometheus', icon: 'prometheus' },
  { name: 'Protractor', icon: 'protractor' },
  { name: 'Pulsar', icon: 'pulsar' },
  { name: 'Pulumi', icon: 'pulumi' },
  { name: 'Puppeteer', icon: 'puppeteer' },
  { name: 'PureScript', icon: 'purescript' },
  { name: 'Putty', icon: 'putty' },
  { name: 'Pycharm', icon: 'pycharm' },
  { name: 'Pypi', icon: 'pypi' },
  { name: 'Pyscript', icon: 'pyscript' },
  { name: 'Pytest', icon: 'pytest' },
  { name: 'Python', icon: 'python' },
  { name: 'Pytorch', icon: 'pytorch' },

  // Q
  { name: 'Qodana', icon: 'qodana' },
  { name: 'Qt', icon: 'qt' },
  { name: 'Quarkus', icon: 'quarkus' },
  { name: 'Quasar', icon: 'quasar' },
  { name: 'Qwik', icon: 'qwik' },

  // R
  { name: 'R', icon: 'r' },
  { name: 'Rabbitmq', icon: 'rabbitmq' },
  { name: 'Rails', icon: 'rails' },
  { name: 'Railway', icon: 'railway' },
  { name: 'Rancher', icon: 'rancher' },
  { name: 'Raspberrypi', icon: 'raspberrypi' },
  { name: 'Reach', icon: 'reach' },
  { name: 'React', icon: 'react' },
  { name: 'React Bootstrap', icon: 'react-bootstrap' },
  { name: 'React Navigation', icon: 'react-navigation' },
  { name: 'React Router', icon: 'react-router' },
  { name: 'Read The Docs', icon: 'read-the-docs' },
  { name: 'Realm', icon: 'realm' },
  { name: 'Rect', icon: 'rect' },
  { name: 'Redhat', icon: 'redhat' },
  { name: 'Redis', icon: 'redis' },
  { name: 'Redux', icon: 'redux' },
  { name: 'Renpy', icon: 'renpy' },
  { name: 'Replit', icon: 'replit' },
  { name: 'Rider', icon: 'rider' },
  { name: 'Rocks DB', icon: 'rocksdb' },
  { name: 'Rocky Linux', icon: 'rockylinux' },
  { name: 'RollUp', icon: 'rollup' },
  { name: 'ros', icon: 'ros' },
  { name: 'RSPEC', icon: 'rspec' },
  { name: 'R Studio', icon: 'rstudio' },
  { name: 'Ruby', icon: 'ruby' },
  { name: 'Rubymine', icon: 'rubymine' },
  { name: 'Rust', icon: 'rust' },
  { name: 'RxJS', icon: 'rxjs' },

  // S
  { name: 'Safari', icon: 'safari' },
  { name: 'Salesforce', icon: 'salesforce' },
  { name: 'Sanity', icon: 'sanity' },
  { name: 'SASS', icon: 'sass' },
  { name: 'Scala', icon: 'scala' },
  { name: 'Scalingo', icon: 'scalingo' },
  { name: 'Scikitlearn', icon: 'scikitlearn' },
  { name: 'SDL', icon: 'sdl' },
  { name: 'Selenium', icon: 'selenium' },
  { name: 'Sema', icon: 'sema' },
  { name: 'Sentry', icon: 'sentry' },
  { name: 'Sequelize', icon: 'sequelize' },
  { name: 'Shopware', icon: 'shopware' },
  { name: 'Shot Grid', icon: 'shotgrid' },
  { name: 'Sketch', icon: 'sketch' },
  { name: 'Slack', icon: 'slack' },
  { name: 'Socket Io', icon: 'socket-io' },
  { name: 'Solidity', icon: 'solidity' },
  { name: 'Solid JS', icon: 'solidjs' },
  { name: 'Sonarqube', icon: 'sonarqube' },
  { name: 'Source Tree', icon: 'sourcetree' },
  { name: 'Spack', icon: 'spack' },
  { name: 'Splunk', icon: 'splunk' },
  { name: 'Spring', icon: 'spring' },
  { name: 'SPSS', icon: 'spss' },
  { name: 'Spyder', icon: 'spyder' },
  { name: 'SQL Alchemy', icon: 'sql-alchemy' },
  { name: 'SQL Developer', icon: 'sql-developer' },
  { name: 'SQLite', icon: 'sqlite' },
  { name: 'SSH', icon: 'ssh' },
  { name: 'Stack Overflow', icon: 'stackoverflow' },
  { name: 'Stata', icon: 'stata' },
  { name: 'Storybook', icon: 'storybook' },
  { name: 'Streamlit', icon: 'streamlit' },
  { name: 'Stylus', icon: 'stylus' },
  { name: 'Subversion', icon: 'subversion' },
  { name: 'Supabase', icon: 'supabase' },
  { name: 'Svelte', icon: 'svelte' },
  { name: 'Swagger', icon: 'swagger' },
  { name: 'Swift', icon: 'swift' },
  { name: 'Swiper', icon: 'swiper' },
  { name: 'Symfony', icon: 'symfony' },

  // T
  { name: 'TailwindCSS', icon: 'tailwindcss' },
  { name: 'Tauri', icon: 'tauri' },
  { name: 'Tensorflow', icon: 'tensorflow' },
  { name: 'Terraform', icon: 'terraform' },
  { name: 'Tex', icon: 'tex' },
  { name: 'The Algorithms', icon: 'thealgorithms' },
  { name: 'Threeds Max', icon: 'threedsmax' },
  { name: 'Threejs', icon: 'threejs' },
  { name: 'Titanium SDK', icon: 'titaniumsdk' },
  { name: 'Tomcat', icon: 'tomcat' },
  { name: 'Tortoise Git', icon: 'tortoisegit' },
  { name: 'Tower Git', icon: 'towergit' },
  { name: 'Traefik Mesh', icon: 'traefikmesh' },
  { name: 'Traefik Proxy', icon: 'traefikproxy' },
  { name: 'Travis', icon: 'travis' },
  { name: 'Trello', icon: 'trello' },
  { name: 'TRPC', icon: 'trpc' },
  { name: 'Twitter', icon: 'twitter' },
  { name: 'Typescript', icon: 'typescript' },
  { name: 'Typo3', icon: 'typo3' },

  // U
  { name: 'Ubuntu', icon: 'ubuntu' },
  { name: 'unified-modeling-language', icon: 'unified-modeling-language' },
  { name: 'Unity', icon: 'unity' },
  { name: 'Unix', icon: 'unix' },
  { name: 'Unreal-engine', icon: 'unreal-engine' },
  { name: 'Uwsgi', icon: 'uwsgi' },

  // V
  { name: 'V8', icon: 'v8' },
  { name: 'Vagrant', icon: 'vagrant' },
  { name: 'Vala', icon: 'vala' },
  { name: 'Vault', icon: 'vault' },
  { name: 'Vercel', icon: 'vercel' },
  { name: 'Vertx', icon: 'vertx' },
  { name: 'Vim', icon: 'vim' },
  { name: 'Visual Basic', icon: 'visual-basic' },
  { name: 'Visual Studio', icon: 'visual-studio' },
  { name: 'Vite', icon: 'vite' },
  { name: 'Vite JS', icon: 'vitejs' },
  { name: 'Vitest', icon: 'vitest' },
  { name: 'Vitess', icon: 'vitess' },
  { name: 'VS code', icon: 'vscode' },
  { name: 'V Sphere', icon: 'vsphere' },
  { name: 'Vue JS', icon: 'vuejs' },
  { name: 'Vue Store Front', icon: 'vue-store-front' },
  { name: 'Vuetify', icon: 'vuetify' },
  { name: 'Vyper', icon: 'vyper' },

  // W
  { name: 'Web Assembly', icon: 'web-assembly' },
  { name: 'Webflow', icon: 'webflow' },
  { name: 'Weblate', icon: 'weblate' },
  { name: 'Webpack', icon: 'webpack' },
  { name: 'Webstorm', icon: 'webstorm' },
  { name: 'Windows 8', icon: 'windows-8' },
  { name: 'Windows 11', icon: 'windows-11' },
  { name: 'Woo Commerce', icon: 'woocommerce' },
  { name: 'Wordpress', icon: 'wordpress' },

  // X
  { name: 'Xamarin', icon: 'xamarin' },
  { name: 'X Code', icon: 'xcode' },
  { name: 'Adobe Xd', icon: 'xd' },
  { name: 'XML', icon: 'xml' },

  // Y
  { name: 'Yaml', icon: 'yaml' },
  { name: 'Yarn', icon: 'yarn' },
  { name: 'Yii', icon: 'yii' },
  { name: 'Yugabyte DB', icon: 'yugabytedb' },
  { name: 'Yunohost', icon: 'yunohost' },

  // Z
  { name: 'Zend', icon: 'zend' },
  { name: 'Zig', icon: 'zig' },
]);

console.log(skillIcons.length);
