<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    width="30"
    height="30"
    style="
      shape-rendering: auto;
      display: block;
      background: rgba(255, 255, 255, 0);
    "
    xmlns:xlink="http://www.w3.org/1999/xlink"
  >
    <g>
      <circle cx="24" cy="50" fill="#06d522" r="26">
        <animate
          attributeName="cx"
          repeatCount="indefinite"
          dur="0.6756756756756757s"
          keyTimes="0;0.5;1"
          values="24;76;24"
          begin="-0.33783783783783783s"
        ></animate>
      </circle>
      <circle cx="76" cy="50" fill="#066ff9" r="26">
        <animate
          attributeName="cx"
          repeatCount="indefinite"
          dur="0.6756756756756757s"
          keyTimes="0;0.5;1"
          values="24;76;24"
          begin="0s"
        ></animate>
      </circle>
      <circle cx="24" cy="50" fill="#06d522" r="26">
        <animate
          attributeName="cx"
          repeatCount="indefinite"
          dur="0.6756756756756757s"
          keyTimes="0;0.5;1"
          values="24;76;24"
          begin="-0.33783783783783783s"
        ></animate>
        <animate
          attributeName="fill-opacity"
          values="0;0;1;1"
          calcMode="discrete"
          keyTimes="0;0.499;0.5;1"
          dur="0.6756756756756757s"
          repeatCount="indefinite"
        ></animate>
      </circle>
      <g></g>
    </g>
    <!-- [ldio] generated by https://loading.io -->
  </svg>
</template>
