export const jobQuery = ref([
  'All',
  'Software Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Fullstack Developer',
  'Data Scientist',
  'DevOps Engineer',
  'Cloud Engineer',
  'Database Administrator',
  'Cybersecurity Specialist',
  'Network Engineer',
  'Machine Learning Engineer',
  'AI Researcher',
  'Mobile App Developer',
  'UI/UX Designer',
  'Product Manager',
  'IT Support Specialist',
  'Systems Administrator',
  'QA Engineer',
  'Blockchain Developer',
  'Site Reliability Engineer',
  'AR/VR Developer',
  'Embedded Systems Engineer',
  'Game Developer',
  'Technical Writer',
  'Business Analyst',
  'IT Project Manager',
  'Solutions Architect',
  'Software Tester',
  'Web Developer',
  'IoT Engineer',
]);
