export const jobQuery = ref([
  { title: 'All Jobs', key: '', action: true },
  { title: 'Software Engineer', key: 'Software Engineer' },
  { title: 'Frontend Developer', key: 'Frontend Developer' },
  { title: 'Backend Developer', key: 'Backend Developer' },
  { title: 'Fullstack Developer', key: 'Fullstack Developer' },
  { title: 'Data Scientist', key: 'Data Scientist' },
  { title: 'DevOps Engineer', key: 'DevOps Engineer' },
  { title: 'Cloud Engineer', key: 'Cloud Engineer' },
  { title: 'Database Administrator', key: 'Database Administrator' },
  { title: 'Cybersecurity Specialist', key: 'Cybersecurity Specialist' },
  { title: 'Network Engineer', key: 'Network Engineer' },
  { title: 'Machine Learning Engineer', key: 'Machine Learning Engineer' },
  { title: 'AI Researcher', key: 'AI Researcher' },
  { title: 'Mobile App Developer', key: 'Mobile App Developer' },
  { title: 'UI/UX Designer', key: 'UI/UX Designer' },
  { title: 'Product Manager', key: 'Product Manager' },
  { title: 'IT Support Specialist', key: 'IT Support Specialist' },
  { title: 'Systems Administrator', key: 'Systems Administrator' },
  { title: 'QA Engineer', key: 'QA Engineer' },
  { title: 'Blockchain Developer', key: 'Blockchain Developer' },
  { title: 'Site Reliability Engineer', key: 'Site Reliability Engineer' },
  { title: 'AR/VR Developer', key: 'AR/VR Developer' },
  { title: 'Embedded Systems Engineer', key: 'Embedded Systems Engineer' },
  { title: 'Game Developer', key: 'Game Developer' },
  { title: 'Technical Writer', key: 'Technical Writer' },
  { title: 'Business Analyst', key: 'Business Analyst' },
  { title: 'IT Project Manager', key: 'IT Project Manager' },
  { title: 'Solutions Architect', key: 'Solutions Architect' },
  { title: 'Software Tester', key: 'Software Tester' },
  { title: 'Web Developer', key: 'Web Developer' },
  { title: 'IoT Engineer', key: 'IoT Engineer' },
]);
