import { DefaultContent } from '../templates/default';
import { useUserStore } from '~/store/user-store';

export const generatePDFTemplate = async () => {
  const { user, fullname } = storeToRefs(useUserStore());
  const PDFMake = usePDFMake();
  const definitions = DefaultContent();

  PDFMake.createPdf(
    {
      content: [
        definitions.headerColumn,
        {
          columns: [
            [definitions.experienceList, definitions.projectList],
            [definitions.educationList, definitions.stackList],
          ],
        },
      ],

      info: {
        title: fullname.value + ' Resumé',
        author: 'QuickHire',
        creator: 'QuickHire',
        producer: 'QuickHire',
        keywords: 'Hiring Software Developers',
      },

      footer: {
        text: 'Generated by QuickHire',
        color: 'gray',
        alignment: 'center',
        margin: 6,
        fontSize: 8,
      },

      styles: {
        brand: {
          color: '#023696',
          bold: true,
        },
        button: {
          display: 'inline',
          color: '#023696',
          padding: 4,
          borderRadius: 4,
        },
      },
      defaultStyle: {
        columnGap: 20,
        fontSize: 10,
        color: '#1E1E1E',
        font: 'Poppins',
      },
    },
    {},
    { Poppins: useFontPresets().Poppins },
  ).download(fullname.value + '-Resumé.pdf');
  return definitions;
};
